### PR TITLE
Map update

### PR DESCRIPTION
**Pull request by anibalsolon**
- Full width
- Not loading in another request, but embedded in the page
- Custom style
- Custom marker
- Abstracting code into a partial

### CODE REVIEW

**Comment by anibalsolon** [comment]
I guess it needs firstly the https://github.com/PESTILLILAB/tacademia.hugo/pull/33 to be checked out

**Comment by bhatiadheeraj** [comment]
We should give the ability to edit the height of the map with markdown

**Comment by anibalsolon** [comment]
That would be good, yes!

**Comment by anibalsolon** [comment]
@bhatiadheeraj forgot to tell, I've made the chances you suggested

**Comment by bhatiadheeraj** [comment]
can you please fix the merge conflict? There is difference of files with main for academia as well as for PESTILLILAB

**Comment by anibalsolon** [comment]
@bhatiadheeraj the PR on tacademia needs to be merged first, so to point to the correct commit in the submodule

**Comment by bhatiadheeraj** [comment]
Updated ! I am sorry I was looking at the wrong comment

**Comment by anibalsolon** [comment]
@bhatiadheeraj all good!

**Pull request merged**
